global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8000']