"""edit media table

Revision ID: 2eb6a1f72f95
Revises: 5b47802533d1
Create Date: 2025-06-24 21:45:30.062922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb6a1f72f95'
down_revision: Union[str, Sequence[str], None] = '5b47802533d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('media', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'thumbnail_url')
    op.drop_column('media', 'file_size')
    op.drop_column('media', 'file_name')
    # ### end Alembic commands ###
